### PR TITLE
Update 19.1-两个时间步的循环神经网络.md

### PR DESCRIPTION
**Pull request by qindagang**
Fix tag not allowed in environment aligned.
Related to this issue [#1286](https://github.com/mathjax/MathJax/issues/1286).
MathJax Plugin for Github _(V0.2.4)_ .
屏幕快照 2020-08-31 15 39 10

### CODE REVIEW

**Review by xiaowuhu — COMMENTED** [review]
{align} cannot work on VScode latex 控件

**Comment by fariyAhill** [comment]
It works on MathJax Plugin for Github.
Also look at these two issues.
https://github.com/KaTeX/KaTeX/issues/1345
https://github.com/KaTeX/KaTeX/issues/2004

**Review by xiaowuhu — COMMENTED** [review]
I'm using VSCode + Markdown All In One extension to write the md file, so I cannot use {align}.
公式8显示不出来的原因是 \tag{8}应该放在 {aligned}外面，已经修改，尚未提交。

**Comment by qindagang** [comment]
I will close this RP.

**Pull request closed without merging**
