### PR TITLE
Create English ReadMe

### PR DESCRIPTION
**Pull request by marko-polo-cheno**
我回来了

What is Golden Dot game?

### CODE REVIEW

**Comment by marko-polo-cheno** [comment]
@xiaowuhu 
Is translation still needed?

**Comment by Livon** [comment]
邮件已收到，祝心情愉快！
-------------------------------------
杨永峰  159-9810-8505

**Comment by xonejyr** [comment]
您好，我是高靖宇
邮件已收到，我会尽快查看并考虑给您回复
谢谢

**Comment by marko-polo-cheno** [comment]
okay, I have not been translating anything in 2022 because this PR was not merged.
超级快的回复 - 谢谢

**Review by xiaowuhu — APPROVED** [review]

**Pull request merged**
