### PR TITLE
More English Translations

### PR DESCRIPTION
**Pull request by marko-polo-cheno**
Please let someone know that **Latex** does not show up correctly in the Chinese and English versions.
This might be an issue for every file.
image

### CODE REVIEW

**Comment by marko-polo-cheno** [comment]
What is the build error?

**Comment by marko-polo-cheno** [comment]
@xiaowuhu Do you know what the CI error is?

**Review by xiaowuhu — APPROVED** [review]

**Comment by xiaowuhu** [comment]
> @xiaowuhu Do you know what the CI error is?

ignore this. a intern setup a CI pipeline to build .md files to readthedoc files.

**Comment by xiaowuhu** [comment]
> Please let someone know that **Latex** does not show up correctly in the Chinese and English versions.
> This might be an issue for every file.
> image

you need to install a plug-in in your browser if you are using chrome to display latex in your browser.

**Pull request merged**
